from __future__ import annotations

import asyncio
from dataclasses import dataclass, field
from typing import Awaitable, Callable

from bot_service.event_args import EventArgs
from bot_service.result import Result

HandlerReturn = Result[str | None, BaseException | None]
ActionHandler = Callable[[EventArgs], Awaitable[HandlerReturn]]


@dataclass(slots=True)
class ActionPolicy:
    stop_on_failure: bool = True


@dataclass(slots=True)
class RegisteredHandler:
    handler_id: str
    callback: ActionHandler
    stop_on_failure: bool | None = None
    timeout_seconds: float | None = None


@dataclass(slots=True)
class ActionRegistration:
    policy: ActionPolicy = field(default_factory=ActionPolicy)
    stages: list[list[RegisteredHandler]] = field(default_factory=list)


class ActionEngine:
    """Event-driven action dispatcher with staged handler execution."""

    def __init__(self) -> None:
        self._actions: dict[str, ActionRegistration] = {}

    def register_action(self, action_name: str, policy: ActionPolicy | None = None) -> None:
        if action_name not in self._actions:
            self._actions[action_name] = ActionRegistration(policy=policy or ActionPolicy())
            return

        if policy is not None:
            self._actions[action_name].policy = policy

    def clear_action(self, action_name: str) -> None:
        if action_name in self._actions:
            self._actions[action_name] = ActionRegistration()

    def clear_all_actions(self) -> None:
        self._actions.clear()

    def list_actions(self) -> list[str]:
        return list(self._actions.keys())

    def register_handler(
        self,
        action_name: str,
        handler_id: str,
        callback: ActionHandler,
        stage: int = 0,
        stop_on_failure: bool | None = None,
        timeout_seconds: float | None = None,
    ) -> None:
        self.register_action(action_name)
        registration = self._actions[action_name]

        while len(registration.stages) <= stage:
            registration.stages.append([])

        existing = next((h for h in registration.stages[stage] if h.handler_id == handler_id), None)
        if existing is not None:
            existing.callback = callback
            existing.stop_on_failure = stop_on_failure
            existing.timeout_seconds = timeout_seconds
            return

        registration.stages[stage].append(
            RegisteredHandler(
                handler_id=handler_id,
                callback=callback,
                stop_on_failure=stop_on_failure,
                timeout_seconds=timeout_seconds,
            )
        )

    def unregister_handler(self, action_name: str, handler_id: str) -> None:
        registration = self._actions.get(action_name)
        if registration is None:
            return

        for stage in registration.stages:
            stage[:] = [h for h in stage if h.handler_id != handler_id]

    def list_handlers(self, action_name: str) -> list[str]:
        registration = self._actions.get(action_name)
        if registration is None:
            return []

        return [handler.handler_id for stage in registration.stages for handler in stage]

    async def dispatch(self, event_args: EventArgs) -> Result[str, BaseException]:
        registration = self._actions.get(event_args.action_name)
        if registration is None or not registration.stages:
            return Result.failure(ValueError(f"No handlers registered for action: {event_args.action_name}"))

        for stage in registration.stages:
            if event_args.cancelled:
                break
            if not stage:
                continue

            stage_results = await asyncio.gather(*(self._run_handler(handler, event_args) for handler in stage))
            for handler, result in zip(stage, stage_results):
                event_args.results[handler.handler_id] = result
                if Result.is_failure(result):
                    should_stop = (
                        handler.stop_on_failure
                        if handler.stop_on_failure is not None
                        else registration.policy.stop_on_failure
                    )
                    if should_stop:
                        event_args.cancel(
                            f"Handler '{handler.handler_id}' failed: {result.error}"
                        )

        if event_args.cancelled and event_args.cancel_reason:
            event_args.add_section(f"⚠️ {event_args.cancel_reason}")

        text = "\n\n".join(event_args.response_sections).strip()
        if not text:
            if event_args.cancel_reason:
                return Result.failure(RuntimeError(event_args.cancel_reason))
            return Result.failure(RuntimeError("No response generated by action handlers"))

        return Result.success(text)

    async def _run_handler(self, handler: RegisteredHandler, event_args: EventArgs) -> HandlerReturn:
        try:
            if handler.timeout_seconds is None:
                result = await handler.callback(event_args)
            else:
                result = await asyncio.wait_for(handler.callback(event_args), timeout=handler.timeout_seconds)
        except TimeoutError:
            return Result.failure(
                TimeoutError(
                    f"Handler '{handler.handler_id}' timed out after {handler.timeout_seconds} seconds"
                )
            )
        except Exception as exc:  # noqa: BLE001
            return Result.failure(exc)

        if Result.is_success(result) and result.data:
            event_args.add_section(result.data)

        return result